<?php

return [
    'shared_key' => env('RFID_SCAN_SHARED_KEY'),
    'allow_open_http' => filter_var(env('RFID_ALLOW_OPEN_HTTP', env('APP_ENV') !== 'production'), FILTER_VALIDATE_BOOL),

    'performance' => [
        'tenant_cache_ttl_seconds' => (int) env('RFID_TENANT_CACHE_TTL_SECONDS', 300),
        'device_cache_ttl_seconds' => (int) env('RFID_DEVICE_CACHE_TTL_SECONDS', 60),
        'device_auth_cache_ttl_seconds' => (int) env('RFID_DEVICE_AUTH_CACHE_TTL_SECONDS', 300),
        'device_seen_throttle_seconds' => (int) env('RFID_DEVICE_SEEN_THROTTLE_SECONDS', 30),
        'always_active_cache_ttl_seconds' => (int) env('RFID_ALWAYS_ACTIVE_CACHE_TTL_SECONDS', 600),
        'mqtt_mode_publish_after_scan_throttle_seconds' => (int) env('RFID_MQTT_MODE_PUBLISH_AFTER_SCAN_THROTTLE_SECONDS', 5),
        'device_event_log_enabled' => filter_var(env('RFID_DEVICE_EVENT_LOG_ENABLED', true), FILTER_VALIDATE_BOOL),
        'require_idempotency_key' => filter_var(env('RFID_REQUIRE_IDEMPOTENCY_KEY', true), FILTER_VALIDATE_BOOL),
        'device_event_cache_ttl_seconds' => (int) env('RFID_DEVICE_EVENT_CACHE_TTL_SECONDS', 3600),
        'sync_batch_max_events' => max(10, min(1000, (int) env('RFID_SYNC_BATCH_MAX_EVENTS', 500))),
        'device_status_online_grace_seconds' => max(30, (int) env('RFID_DEVICE_STATUS_ONLINE_GRACE_SECONDS', 120)),
    ],

    'mqtt' => [
        'enabled' => filter_var(env('RFID_MQTT_BRIDGE_ENABLED', false), FILTER_VALIDATE_BOOL),
        'host' => env('RFID_MQTT_HOST', ''),
        'port' => (int) env('RFID_MQTT_PORT', 8883),
        'username' => env('RFID_MQTT_USERNAME', ''),
        'password' => env('RFID_MQTT_PASSWORD', ''),
        'client_id_prefix' => env('RFID_MQTT_CLIENT_ID_PREFIX', 'edusmart-rfid-bridge'),
        'qos' => (int) env('RFID_MQTT_QOS', 1),
        'connect_timeout' => (int) env('RFID_MQTT_CONNECT_TIMEOUT', 20),
        'socket_timeout' => (int) env('RFID_MQTT_SOCKET_TIMEOUT', 5),
        'keep_alive' => (int) env('RFID_MQTT_KEEP_ALIVE', 20),
        'reconnect_delay_seconds' => (int) env('RFID_MQTT_RECONNECT_DELAY', 5),
        'mode_sync_interval_seconds' => (int) env('RFID_MQTT_MODE_SYNC_INTERVAL', 20),
        'config_reload_interval_seconds' => (int) env('RFID_MQTT_CONFIG_RELOAD_INTERVAL', 60),
        'max_payload_bytes' => max(512, min(65536, (int) env('RFID_MQTT_MAX_PAYLOAD_BYTES', 8192))),

        'use_tls' => filter_var(env('RFID_MQTT_USE_TLS', true), FILTER_VALIDATE_BOOL),
        'tls_verify_peer' => filter_var(env('RFID_MQTT_TLS_VERIFY_PEER', true), FILTER_VALIDATE_BOOL),
        'tls_verify_peer_name' => filter_var(env('RFID_MQTT_TLS_VERIFY_PEER_NAME', true), FILTER_VALIDATE_BOOL),
        'tls_allow_self_signed' => filter_var(env('RFID_MQTT_TLS_ALLOW_SELF_SIGNED', false), FILTER_VALIDATE_BOOL),

        'scan_topic_template' => env('RFID_MQTT_SCAN_TOPIC_TEMPLATE', 'edusmart/{tenant}/rfid/{device}/scan'),
        'scan_topic_filter' => env('RFID_MQTT_SCAN_TOPIC_FILTER', ''),
        'response_topic_template' => env('RFID_MQTT_RESPONSE_TOPIC_TEMPLATE', 'edusmart/{tenant}/rfid/{device}/response'),
        'mode_topic_template' => env('RFID_MQTT_MODE_TOPIC_TEMPLATE', 'edusmart/{tenant}/rfid/{device}/mode'),

        'default_tenant_slug' => env('RFID_MQTT_DEFAULT_TENANT_SLUG', ''),
        'device_tenant_map' => env('RFID_MQTT_DEVICE_TENANT_MAP', '{}'),
    ],

    'mosquitto' => [
        'enabled' => filter_var(env('RFID_MOSQUITTO_ENABLED', true), FILTER_VALIDATE_BOOL),
        'public_host' => env('RFID_MOSQUITTO_PUBLIC_HOST', ''),
        'public_port' => (int) env('RFID_MOSQUITTO_PUBLIC_PORT', 8883),
        'public_use_tls' => filter_var(env('RFID_MOSQUITTO_PUBLIC_USE_TLS', true), FILTER_VALIDATE_BOOL),
        'internal_host' => env('RFID_MOSQUITTO_INTERNAL_HOST', 'mosquitto'),
        'internal_port' => (int) env('RFID_MOSQUITTO_INTERNAL_PORT', 1883),
        'internal_use_tls' => filter_var(env('RFID_MOSQUITTO_INTERNAL_USE_TLS', false), FILTER_VALIDATE_BOOL),
        'bridge_username' => env('RFID_MOSQUITTO_BRIDGE_USERNAME', 'edusmart_bridge'),
        'bridge_password' => env('RFID_MOSQUITTO_BRIDGE_PASSWORD', ''),
        'tenant_username_prefix' => env('RFID_MOSQUITTO_TENANT_USERNAME_PREFIX', 'edusmart'),
        'topic_prefix' => env('RFID_MOSQUITTO_TOPIC_PREFIX', 'edusmart'),
        'password_length' => (int) env('RFID_MOSQUITTO_TENANT_PASSWORD_LENGTH', 40),
        'passwd_binary' => env('RFID_MOSQUITTO_PASSWD_BINARY', 'mosquitto_passwd'),
        'file_uid' => (int) env('RFID_MOSQUITTO_FILE_UID', 82),
        'file_gid' => (int) env('RFID_MOSQUITTO_FILE_GID', 82),
        'file_mode' => env('RFID_MOSQUITTO_FILE_MODE', '0660'),
        'password_file' => env('RFID_MOSQUITTO_PASSWORD_FILE', '/var/www/html/mosquitto/passwords'),
        'acl_file' => env('RFID_MOSQUITTO_ACL_FILE', '/var/www/html/mosquitto/aclfile'),
    ],
];
