[program:edusmart-worker]
command=/usr/bin/php /var/www/edusmart/backend/artisan queue:work redis --sleep=1 --tries=3 --timeout=120 --max-time=3600
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
directory=/var/www/edusmart/backend
redirect_stderr=true
stdout_logfile=/var/log/supervisor/edusmart-worker.log
stopwaitsecs=3600
