[program:edusmart-app]
command=/usr/bin/php /var/www/edusmart/backend/artisan serve --host=127.0.0.1 --port=8000
process_name=%(program_name)s
directory=/var/www/edusmart/backend
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/edusmart-app.log
stopwaitsecs=60
