[program:edusmart-scheduler]
command=/bin/sh -c 'while true; do /usr/bin/php /var/www/edusmart/backend/artisan schedule:run --verbose --no-interaction; sleep 60; done'
process_name=%(program_name)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/edusmart-scheduler.log
stopwaitsecs=60
