allow_anonymous false
password_file /mosquitto/config/generated/passwords
acl_file /mosquitto/config/generated/aclfile

persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages false
allow_zero_length_clientid false

listener 1883 0.0.0.0
max_connections 200
max_inflight_messages 20
max_queued_messages 100
max_packet_size 65536
max_qos 1
max_keepalive 300

listener 8883 0.0.0.0
max_connections 200
max_inflight_messages 20
max_queued_messages 100
max_packet_size 65536
max_qos 1
max_keepalive 300
certfile /mosquitto/config/generated/certs/server.crt
keyfile /mosquitto/config/generated/certs/server.key
tls_version tlsv1.2
