// src/components/Navbar/icons.jsx
import React from 'react'
import {
  Award,
  BarChart3,
  BookOpen,
  Brain,
  CalendarDays,
  CheckCircle2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Database,
  GraduationCap,
  Gauge,
  HardDrive,
  History,
  Home,
  ListChecks,
  LogOut,
  Menu,
  MessageCircle,
  Monitor,
  PencilLine,
  Palette,
  ScanLine,
  School,
  Settings,
  ShieldCheck,
  Signal,
  TerminalSquare,
  UserRound,
  UsersRound,
  Workflow,
  X,
} from 'lucide-react'

const iconComponents = {
  home: Home,
  calendar: CalendarDays,
  check: CheckCircle2,
  checkSmall: Check,
  brain: Brain,
  book: BookOpen,
  chart: BarChart3,
  user: UserRound,
  school: School,
  scan: ScanLine,
  history: History,
  certificate: Award,
  backup: Database,
  cog: Settings,
  logout: LogOut,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  monitor: Monitor,
  shield: ShieldCheck,
  signal: Signal,
  terminal: TerminalSquare,
  pencil: PencilLine,
  theme: Palette,
  users: UsersRound,
  teacher: GraduationCap,
  chat: MessageCircle,
  storage: HardDrive,
  menu: Menu,
  x: X,
  workflow: Workflow,
  queue: ListChecks,
  gauge: Gauge,
}

export const Icon = React.memo(({ name, className = 'w-5 h-5' }) => {
  const Component = iconComponents[name] || Circle
  return <Component aria-hidden="true" className={className} strokeWidth={1.8} />
})

Icon.displayName = 'Icon'
